import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HeaderComponent } from "./components/layouts/Header";
import { ThemeProvider } from "@/app/providers/theme-provider";
import Footer from "./components/layouts/Footer";
import { productService } from "@/services/product.services";
import { DEFAULT_SEARCH_QUERY } from "@/constants/requestTypes";
import { ProductProvider } from "./providers/products-provider";
import "./globals.css";
import { createSession } from "@/lib/session";

import { CookiesProvider } from "next-client-cookies/server";
import CartProvider from "./providers/cart-provider";
import { CartServices } from "@/services/cart.services";
import { UUID } from "crypto";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const productResponse = await productService.searchProduct(DEFAULT_SEARCH_QUERY)
  if (!productResponse) return <div className="flex items-center justify-center">Loading...</div>

  const cartResponse = await CartServices.createSession(crypto.randomUUID() as UUID)
  if (!cartResponse) return <div className="flex items-center justify-center">Could not generate Cart...</div>

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
          <body className="flex flex-col min-h-screen justify-between">
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <ProductProvider initialData={productResponse}>
                <CookiesProvider>
                  <CartProvider cartData={cartResponse}>
                    <HeaderComponent />
                    {children}
                  </CartProvider>
                </CookiesProvider>
              </ProductProvider>
            </ThemeProvider>
            <Footer />
          </body>
    </html>
  );
}
